# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew. DO NOT EDIT.
# Instead, please update the formula to use the latest version.
class AirconnectInstaller < Formula
  desc "Installer script for AirConnect - AirPlay bridge for Chromecast and UPnP players"
  homepage "https://github.com/MacsInSpace/AirConnectInstaller"
  # Download from a specific tag/release (recommended for stability)
  url "https://github.com/MacsInSpace/AirConnectInstaller/archive/refs/tags/v1.0.0.tar.gz"
  version "1.0.0"
  # TODO: Calculate SHA256 after creating the release tag:
  # curl -L https://github.com/MacsInSpace/AirConnectInstaller/archive/refs/tags/v1.0.0.tar.gz | shasum -a 256
  sha256 "" # Update this after creating v1.0.0 tag
  license "MIT"

  def install
    # Install the script as an executable command
    bin.install "install.sh" => "airconnect-install"
    # Make sure it's executable
    chmod 0755, bin/"airconnect-install"
  end

  test do
    # Test that the script exists and is executable
    assert_predicate bin/"airconnect-install", :exist?
    # Test that it shows usage info (script will exit with error without sudo, which is expected)
    output = shell_output("#{bin}/airconnect-install 2>&1", 1)
    assert_match "AirConnect Installer", output
  end

  def caveats
    <<~EOS
      This installer requires root privileges to install AirConnect.
      
      To install AirConnect, run:
        sudo airconnect-install
      
      The installer will:
      - Download the latest AirConnect release from GitHub
      - Install binaries to /usr/local/bin
      - Set up launchd services for automatic startup
      - Configure OpenSSL symlinks if Homebrew is installed
      
      Logs will be available at:
      - /var/log/aircast.log
      - /var/log/airupnp.log
    EOS
  end
end

